//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//Mikkel//Documents//UNI//4. Semester//CalculatorLanguage//AntlrCSharp//langName.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="langNameParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IlangNameVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] langNameParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] langNameParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] langNameParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] langNameParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] langNameParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] langNameParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] langNameParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] langNameParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] langNameParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssignment([NotNull] langNameParser.VariableAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForLoop([NotNull] langNameParser.ForLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.crementer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCrementer([NotNull] langNameParser.CrementerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare([NotNull] langNameParser.CompareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclaration([NotNull] langNameParser.ArrayDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.arrayAssignement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAssignement([NotNull] langNameParser.ArrayAssignementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] langNameParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.arrayDeclaration2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclaration2d([NotNull] langNameParser.ArrayDeclaration2dContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.arrayAssignment2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAssignment2d([NotNull] langNameParser.ArrayAssignment2dContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.arrayAccess2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess2d([NotNull] langNameParser.ArrayAccess2dContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] langNameParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.randomStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRandomStatement([NotNull] langNameParser.RandomStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.fileWriteStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileWriteStatement([NotNull] langNameParser.FileWriteStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.fileWriteNewline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileWriteNewline([NotNull] langNameParser.FileWriteNewlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.mapDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapDeclaration([NotNull] langNameParser.MapDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.mapPrint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapPrint([NotNull] langNameParser.MapPrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.mapModification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapModification([NotNull] langNameParser.MapModificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.mapWrite"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapWrite([NotNull] langNameParser.MapWriteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.mapBSP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapBSP([NotNull] langNameParser.MapBSPContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.mapObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapObject([NotNull] langNameParser.MapObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="langNameParser.mapTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapTest([NotNull] langNameParser.MapTestContext context);
}
