//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//Mikkel//Documents//UNI//4. Semester//CalculatorLanguage//AntlrCSharp//Mapper.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MapperParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMapperVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] MapperParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MapperParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.calculation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalculation([NotNull] MapperParser.CalculationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MapperParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] MapperParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] MapperParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] MapperParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] MapperParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] MapperParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] MapperParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssignment([NotNull] MapperParser.VariableAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForLoop([NotNull] MapperParser.ForLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.crementer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCrementer([NotNull] MapperParser.CrementerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.compare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare([NotNull] MapperParser.CompareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclaration([NotNull] MapperParser.ArrayDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.arrayAssignement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAssignement([NotNull] MapperParser.ArrayAssignementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] MapperParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.arrayDeclaration2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclaration2d([NotNull] MapperParser.ArrayDeclaration2dContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.arrayAssignment2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAssignment2d([NotNull] MapperParser.ArrayAssignment2dContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.arrayAccess2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess2d([NotNull] MapperParser.ArrayAccess2dContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] MapperParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.randomStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRandomStatement([NotNull] MapperParser.RandomStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.fileWriteStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileWriteStatement([NotNull] MapperParser.FileWriteStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.fileWriteNewline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileWriteNewline([NotNull] MapperParser.FileWriteNewlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.mapDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapDeclaration([NotNull] MapperParser.MapDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.mapAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapAccess([NotNull] MapperParser.MapAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.mapModification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapModification([NotNull] MapperParser.MapModificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.mapPrint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapPrint([NotNull] MapperParser.MapPrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.mapBSP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapBSP([NotNull] MapperParser.MapBSPContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.mapObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapObject([NotNull] MapperParser.MapObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapperParser.mapTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapTest([NotNull] MapperParser.MapTestContext context);
}
